### ISSUE TITLE
Demote staticxml backend to support unit tests only

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#368]
Although the staticxml backend is included in the production build, it is not used productively. It was intended as a way to serve OSM data from an XML file in a read-only scenario. However, memory consumption and performance limit the file sizes significantly. In the end, it is not really suitable for productive use.

Proposed changes:

- [x] Move staticxml* backend to test/ directory for exclusive use in unit tests (DONE: -> #376)
- [x] Remove  multi backend concept, assume ApiDB as the only (remaining) backend available (DONE: -> #395)
- [x] Remove ENABLE_APIDB compile flag, since we need at least one backend (DONE: -> #395)

Part of https://github.com/mmd-osm/openstreetmap-cgimap/tree/patch/staticxml_test
